#pragma once

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    BOARD_WAVE_175C_PET_EXPRESSION_SLEEPY = 0,
    BOARD_WAVE_175C_PET_EXPRESSION_IDLE,
    BOARD_WAVE_175C_PET_EXPRESSION_HAPPY,
    BOARD_WAVE_175C_PET_EXPRESSION_LISTENING,
    BOARD_WAVE_175C_PET_EXPRESSION_THINKING,
    BOARD_WAVE_175C_PET_EXPRESSION_SPEAKING,
    BOARD_WAVE_175C_PET_EXPRESSION_SAD,
    BOARD_WAVE_175C_PET_EXPRESSION_SHY,
    BOARD_WAVE_175C_PET_EXPRESSION_FRUSTRATED,
    BOARD_WAVE_175C_PET_EXPRESSION_BOUNCING,
    BOARD_WAVE_175C_PET_EXPRESSION_LAUGHING,
    BOARD_WAVE_175C_PET_EXPRESSION_CRYING,
    BOARD_WAVE_175C_PET_EXPRESSION_CURIOUS,
    BOARD_WAVE_175C_PET_EXPRESSION_WORRIED,
    BOARD_WAVE_175C_PET_EXPRESSION_COUNT,
} board_wave_175c_pet_expression_t;

#ifdef __cplusplus
}
#endif
